// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdBdH9jCU3dnQ8d9WT-veUoVefVUGrk8',
    appId: '1:1076236209612:web:b6f8e0138810f0107aa169',
    messagingSenderId: '1076236209612',
    projectId: 'profolio-abhishek-shelar',
    databaseURL: "https://profolio-abhishek-shelar-default-rtdb.firebaseio.com/",  // remove this line
    authDomain: 'profolio-abhishek-shelar.firebaseapp.com',
    storageBucket: 'profolio-abhishek-shelar.firebasestorage.app',
    measurementId: 'G-RS6S8GQ44D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-krr3fam5stkXyIyW8Gxu-xYjeQP5P4',
    appId: '1:1076236209612:android:52b191d53e03491a7aa169',
    messagingSenderId: '1076236209612',
    databaseURL: "https://profolio-abhishek-shelar-default-rtdb.firebaseio.com/",  // remove this line
    projectId: 'profolio-abhishek-shelar',
    storageBucket: 'profolio-abhishek-shelar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAml6YrojHLXmpeJoEgq1LYudNUIwxClfY',
    appId: '1:1076236209612:ios:b779d9532e917dce7aa169',
    messagingSenderId: '1076236209612',
    databaseURL: "https://profolio-abhishek-shelar-default-rtdb.firebaseio.com/",  // remove this line
    projectId: 'profolio-abhishek-shelar',
    storageBucket: 'profolio-abhishek-shelar.firebasestorage.app',
    iosBundleId: 'com.example.profolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAml6YrojHLXmpeJoEgq1LYudNUIwxClfY',
    appId: '1:1076236209612:ios:b779d9532e917dce7aa169',
    messagingSenderId: '1076236209612',
    projectId: 'profolio-abhishek-shelar',
    storageBucket: 'profolio-abhishek-shelar.firebasestorage.app',
    iosBundleId: 'com.example.profolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIdBdH9jCU3dnQ8d9WT-veUoVefVUGrk8',
    appId: '1:1076236209612:web:9a037aa5b43216887aa169',
    messagingSenderId: '1076236209612',
    databaseURL: "https://profolio-abhishek-shelar-default-rtdb.firebaseio.com/",  // remove this line
    projectId: 'profolio-abhishek-shelar',
    authDomain: 'profolio-abhishek-shelar.firebaseapp.com',
    storageBucket: 'profolio-abhishek-shelar.firebasestorage.app',
    measurementId: 'G-SLMYHV5B39',
  );

}